# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /codex-cli
      - /codex-rs/responses-api-proxy/npm
      - /.devcontainer/codex-install
      - /sdk/typescript
      - /shell-tool-mcp
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
  - package-ecosystem: cargo
    directories:
      - /codex-rs
      - /tools/argument-comment-lint
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
  - package-ecosystem: pip
    directories:
      - /scripts
      - /sdk/python
      - /sdk/python-runtime
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
  - package-ecosystem: docker
    directories:
      - /.devcontainer
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
  - package-ecosystem: rust-toolchain
    directories:
      - /codex-rs
      - /tools/argument-comment-lint
    schedule:
      interval: daily
      time: "03:00"
      timezone: Etc/UTC
