// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentNotificationContent } from "./AgentNotificationContent";
import type { AgentNotificationOrigin } from "./AgentNotificationOrigin";

export type AgentNotificationSummary = { communicationId: string | null, sequence: bigint, origin: AgentNotificationOrigin, senderAgentPath: string, senderThreadId: string | null, content: AgentNotificationContent, };
