// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDeliveryIntent } from "./AgentDeliveryIntent";
import type { AgentWakeCause } from "./AgentWakeCause";

export type AgentDeliveryDisposition = { intent: AgentDeliveryIntent, enqueuedAtMs?: bigint, endedActiveWait: boolean, waitId?: string, targetSetRelation?: string, parentTurnStarted?: boolean, deliveredToModelAtMs?: bigint, deliveredTurnId?: string, displayedAtMs?: bigint, actualWakeCause?: AgentWakeCause, queuedUpdateCount?: number, };
