// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentWakeCause = "operator_message" | "child_actionable_message" | "child_terminal_transition" | "unrelated_mailbox_event" | "timeout_lease_expiry" | "cancellation_interruption" | "persistent_goal_continuation" | "runtime_system_event";
