// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentDeliveryIntent = "queue_only" | "actionable_wake_requested" | "terminal_handoff" | "interrupt_emergency";
