// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDeliveryIntent } from "./AgentDeliveryIntent";
import type { AgentWakeCause } from "./AgentWakeCause";

export type AgentDeliveryDisposition = { intent: AgentDeliveryIntent, enqueuedAtMs?: number | null, endedActiveWait: boolean, waitId?: string | null, targetSetRelation?: string | null, parentTurnStarted?: boolean | null, deliveredToModelAtMs?: number | null, deliveredTurnId?: string | null, displayedAtMs?: number | null, actualWakeCause?: AgentWakeCause | null, queuedUpdateCount?: number | null, };
