// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentStatus } from "./CollabAgentStatus";

export type CollabAgentState = { status: CollabAgentStatus, message: string | null, /**
 * V1 lifecycle events identify agents by nickname and role before the child thread starts.
 * V2 agent paths remain available through `SubAgentActivity`.
 */
agentNickname?: string, agentRole?: string, };
