// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerUseCallOutputContentItem } from "./ComputerUseCallOutputContentItem";

/**
 * Result returned by a native computer-use caller.
 */
export type ComputerUseCallResponse = { contentItems: Array<ComputerUseCallOutputContentItem>, success: boolean, };
