// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Parameters for a native computer-use call delegated to the client.
 */
export type ComputerUseCallParams = { threadId: string, turnId: string, callId: string, environmentId: string | null, adapter: string, tool: string, arguments: JsonValue, };
