// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadUsageSummaryTotals = { providerCallCount: bigint, unpricedCallCount: bigint, partial: boolean, uncachedInputTokens: bigint, cachedInputTokens: bigint, cacheWriteInputTokens: bigint, outputTokens: bigint, totalTokens: bigint, providerReportedCredits: number | null, estimatedTotalCredits: number | null, pricedCreditsTotal: number | null,
/**
 * `complete`, `partial`, or `unavailable` for the full family.
 */
creditCoverage: string, };
