// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadLoadedListResponse = {
/**
 * Thread ids for sessions currently loaded in memory.
 */
data: Array<string>,
/**
 * True only when the server applied the requested `ancestorThreadId` filter.
 *
 * Older servers omit this field. Clients must treat an omitted acknowledgement as false.
 */
ancestorFilterApplied?: boolean,
/**
 * Opaque cursor to pass unchanged as `cursor` on the next call. Its representation and
 * page boundary are server-defined. If it is null, there are no more items to return.
 */
nextCursor: string | null, };
