// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSource } from "./ThreadSource";

export type ThreadUsageSummaryNode = { threadId: string, parentThreadId: string | null, rootThreadId: string, forkParentThreadId: string | null, spawnRequestId: string | null, threadSource: ThreadSource | null,
/**
 * `root`, `fork`, `agent_spawn`, or `unknown`.
 */
lineageEdgeKind: string,
/**
 * `persisted`, `inferred`, or `unknown`.
 */
lineageConfidence: string, agentNickname: string | null, agentRole: string | null, createdAt: string | null, lastActivityAt: string | null, modelsUsed: string | null, serviceTiersUsed: string | null, providerCallCount: bigint, unpricedCallCount: bigint, partial: boolean, uncachedInputTokens: bigint, cachedInputTokens: bigint, cacheWriteInputTokens: bigint, outputTokens: bigint, totalTokens: bigint, providerReportedCredits: number | null, estimatedTotalCredits: number | null, pricedCreditsTotal: number | null, };
