// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadLoadedListParams = {
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size. When omitted, the server returns its bounded default of 100 sessions.
 * Provided values are clamped to the inclusive range 1..=100. Follow `nextCursor` to
 * continue when more loaded sessions remain.
 */
limit?: number | null,
/**
 * Optional loaded thread-spawn ancestor. When set, returns only currently loaded
 * descendants of that thread.
 */
ancestorThreadId?: string | null, };
