// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

export type TurnCompletedNotification = { threadId: string, turn: Turn,
/**
 * Final model used after server-side routing or fallback.
 */
finalModel: string | null,
/**
 * Concrete resolved model snapshot used to execute the turn.
 */
modelSnapshot: string | null, };
