use crate::ThreadId;
use serde::Deserialize;
use serde::Serialize;

const AUTOMATIC_TURN_CLIENT_ID_PREFIX: &str = "automatic-turn:v1:";
const AUTOMATIC_TURN_CLIENT_ID_MAX_BYTES: usize = 1024;
/// Internal transport marker used to carry a server-issued capability through the existing
/// app-server error-details field without changing the public error schema.
pub const AUTOMATIC_TURN_CAPABILITY_DETAILS_PREFIX: &str = "automatic-turn-capability:v1:";

/// Model-opaque metadata for a user turn generated by an automatic policy retry.
///
/// The value is carried in `client_user_message_id` for compatibility with existing clients. It
/// is an untrusted transport envelope: the server must validate it against the actual thread and
/// an eligible preceding policy event before recording provenance.
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AutomaticTurnOrigin {
    PolicyRetry,
}

impl AutomaticTurnOrigin {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::PolicyRetry => "policy_retry",
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct AutomaticTurnProvenance {
    pub origin: AutomaticTurnOrigin,
    pub thread_id: String,
    pub trigger_turn_id: String,
    pub attempt: u8,
    pub max_attempts: u8,
    /// Opaque capability issued by the server for one pending automatic operation.
    ///
    /// This is deliberately carried alongside the legacy client-id envelope. A syntactically
    /// valid envelope without the capability is never eligible for server projection.
    pub capability: String,
}

impl AutomaticTurnProvenance {
    pub fn capability_details(trigger_turn_id: &str, capability: &str) -> Option<String> {
        let trigger_turn_id = trigger_turn_id.trim();
        let capability = capability.trim();
        (!trigger_turn_id.is_empty() && !capability.is_empty()).then(|| {
            let payload = serde_json::json!({
                "trigger_turn_id": trigger_turn_id,
                "capability": capability,
            });
            format!("{AUTOMATIC_TURN_CAPABILITY_DETAILS_PREFIX}{payload}")
        })
    }

    pub fn capability_from_details(details: Option<&str>) -> Option<String> {
        Self::trigger_and_capability_from_details(details).map(|(_, capability)| capability)
    }

    pub fn trigger_and_capability_from_details(details: Option<&str>) -> Option<(String, String)> {
        let payload = details?.strip_prefix(AUTOMATIC_TURN_CAPABILITY_DETAILS_PREFIX)?;
        let payload: serde_json::Value = serde_json::from_str(payload).ok()?;
        let trigger_turn_id = payload.get("trigger_turn_id")?.as_str()?.trim();
        let capability = payload.get("capability")?.as_str()?.trim();
        (!trigger_turn_id.is_empty() && !capability.is_empty())
            .then(|| (trigger_turn_id.to_string(), capability.to_string()))
    }

    pub fn policy_retry(
        thread_id: ThreadId,
        trigger_turn_id: impl Into<String>,
        attempt: u8,
        max_attempts: u8,
        capability: impl Into<String>,
    ) -> Option<Self> {
        let provenance = Self {
            origin: AutomaticTurnOrigin::PolicyRetry,
            thread_id: thread_id.to_string(),
            trigger_turn_id: trigger_turn_id.into(),
            attempt,
            max_attempts,
            capability: capability.into(),
        };
        provenance.is_well_formed().then_some(provenance)
    }

    /// Encode an envelope for transport through the existing client-id field.
    pub fn to_client_user_message_id(&self) -> Option<String> {
        if !self.is_well_formed() {
            return None;
        }
        let payload = serde_json::to_string(self).ok()?;
        let client_id = format!("{AUTOMATIC_TURN_CLIENT_ID_PREFIX}{payload}");
        (client_id.len() <= AUTOMATIC_TURN_CLIENT_ID_MAX_BYTES).then_some(client_id)
    }

    /// Decode a transport envelope. The result is untrusted until a server/runtime boundary
    /// validates it against the actual thread and an eligible policy event.
    pub fn decode_client_user_message_id(client_id: &str) -> Option<Self> {
        if client_id.len() > AUTOMATIC_TURN_CLIENT_ID_MAX_BYTES {
            return None;
        }
        let payload = client_id.strip_prefix(AUTOMATIC_TURN_CLIENT_ID_PREFIX)?;
        let provenance: Self = serde_json::from_str(payload).ok()?;
        provenance.is_well_formed().then_some(provenance)
    }

    fn is_well_formed(&self) -> bool {
        !self.thread_id.trim().is_empty()
            && ThreadId::from_string(&self.thread_id).is_ok()
            && !self.trigger_turn_id.trim().is_empty()
            && !self.capability.trim().is_empty()
            && self.attempt > 0
            && self.max_attempts > 0
            && self.attempt <= self.max_attempts
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn policy_retry_round_trips_as_bounded_transport_metadata() {
        let thread_id = ThreadId::new();
        let provenance = AutomaticTurnProvenance::policy_retry(
            thread_id,
            "turn-trigger",
            /*attempt*/ 2,
            /*max_attempts*/ 3,
            /*capability*/ "server-capability",
        )
        .expect("valid provenance");
        let client_id = provenance
            .to_client_user_message_id()
            .expect("bounded client id");

        assert!(client_id.starts_with(AUTOMATIC_TURN_CLIENT_ID_PREFIX));
        assert!(!client_id.contains("message"));
        assert_eq!(
            AutomaticTurnProvenance::decode_client_user_message_id(&client_id),
            Some(provenance)
        );
    }

    #[test]
    fn decoder_rejects_forged_prefix_and_invalid_attempt_shapes() {
        assert!(AutomaticTurnProvenance::decode_client_user_message_id("human-message").is_none());
        assert!(
            AutomaticTurnProvenance::decode_client_user_message_id("automatic-turn:v2:{}")
                .is_none()
        );

        let thread_id = ThreadId::new();
        let valid = AutomaticTurnProvenance::policy_retry(
            thread_id,
            "turn-trigger",
            /*attempt*/ 1,
            /*max_attempts*/ 3,
            /*capability*/ "server-capability",
        )
        .expect("valid provenance")
        .to_client_user_message_id()
        .expect("bounded client id");
        let invalid_attempt = format!(
            "automatic-turn:v1:{{\"origin\":\"policy_retry\",\"thread_id\":\"{thread_id}\",\"trigger_turn_id\":\"turn-trigger\",\"attempt\":4,\"max_attempts\":3,\"capability\":\"server-capability\"}}",
        );
        assert!(AutomaticTurnProvenance::decode_client_user_message_id(&invalid_attempt).is_none());
        // A syntactically valid envelope is intentionally still untrusted; the runtime validates
        // its thread and trigger against server-owned eligibility state.
        assert!(AutomaticTurnProvenance::decode_client_user_message_id(&valid).is_some());
    }

    #[test]
    fn capability_details_round_trip_trigger_identity() {
        let details = AutomaticTurnProvenance::capability_details("same-turn#2", "opaque-token")
            .expect("non-empty capability details");
        assert_eq!(
            AutomaticTurnProvenance::trigger_and_capability_from_details(Some(&details)),
            Some(("same-turn#2".to_string(), "opaque-token".to_string(),))
        );
        assert!(
            AutomaticTurnProvenance::trigger_and_capability_from_details(/*details*/ None)
                .is_none()
        );
    }
}
