#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

# Bazel wildcard builds skip manual targets, which misses the internal
# `*-unit-tests-bin` rust_test targets generated by `codex_rust_crate()`.
# Add only those manual rust_test targets explicitly so inline `#[cfg(test)]`
# call sites are linted without pulling in unrelated manual release targets.
manual_rust_test_targets="$(
  ./.github/scripts/run-bazel-query-ci.sh \
    --output=label \
    -- 'kind("rust_test rule", attr(tags, "manual", //codex-rs/...))'
)"
if [[ "${RUNNER_OS:-}" != "Windows" ]]; then
  manual_rust_test_targets="$(printf '%s\n' "${manual_rust_test_targets}" | grep -v -- '-windows-cross-bin$' || true)"
fi

# Convert semantic lint opt-outs into negative target patterns so wildcard
# builds do not analyze toolchains used only by those wrappers.
excluded_targets="$(
  ./.github/scripts/run-bazel-query-ci.sh \
    --output=label \
    -- 'attr(tags, "no-argument-comment-lint", //codex-rs/...)'
)"

# The lint configuration does not register the transitioned Windows toolchain.
# The V8 proof-of-concept pulls in the full native rusty_v8/ICU graph in cold
# hosted frontier runs, which can consume the whole lane before linting ordinary
# Rust call sites. Keep it covered by build/test workflows instead of this lint.
printf '%s\n' \
  "//codex-rs/..." \
  "-//codex-rs/v8-poc/..." \
  "-//codex-rs/core/tests/remote_env_windows:smoke-test"
if [[ -n "${excluded_targets}" ]]; then
  printf '%s\n' "${excluded_targets}" | sed 's/^/-/'
fi
printf '%s\n' "${manual_rust_test_targets}"
