#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

# The V8-backed Rust crates force a native V8/ICU compile before the Rust lint
# can run. Dedicated V8 workflows cover that build surface; argument-comment
# lint should stay focused on Rust call-site coverage.
v8_backed_target_patterns=(
  "-//codex-rs/code-mode/..."
  "-//codex-rs/v8-poc/..."
)

# Bazel wildcard builds skip manual targets, which misses the internal
# `*-unit-tests-bin` rust_test targets generated by `codex_rust_crate()`.
# Add only those manual rust_test targets explicitly so inline `#[cfg(test)]`
# call sites are linted without pulling in unrelated manual release targets.
manual_rust_test_targets="$(
  ./.github/scripts/run-bazel-query-ci.sh \
    --output=label \
    -- 'kind("rust_test rule", attr(tags, "manual", //codex-rs/...))'
)"
for target_pattern in "${v8_backed_target_patterns[@]}"; do
  package_prefix="${target_pattern#-//}"
  package_prefix="${package_prefix%/...}"
  manual_rust_test_targets="$(printf '%s\n' "${manual_rust_test_targets}" | grep -v -- "^//${package_prefix}/" || true)"
done
if [[ "${RUNNER_OS:-}" != "Windows" ]]; then
  manual_rust_test_targets="$(printf '%s\n' "${manual_rust_test_targets}" | grep -v -- '-windows-cross-bin$' || true)"
fi

printf '%s\n' "//codex-rs/..."
printf '%s\n' "${v8_backed_target_patterns[@]}"
printf '%s\n' "${manual_rust_test_targets}"
