//! Configuration object accepted by the `codex` MCP tool-call.

use codex_arg0::Arg0DispatchPaths;
use codex_core::config::Config;
use codex_core::config::ConfigOverrides;
use codex_protocol::ThreadId;
use codex_protocol::config_types::SandboxMode;
use codex_protocol::protocol::AskForApproval;
use codex_utils_json_to_toml::json_to_toml;
use rmcp::model::JsonObject;
use rmcp::model::Tool;
use schemars::JsonSchema;
use schemars::Schema;
use schemars::generate::SchemaSettings;
use serde::Deserialize;
use serde::Serialize;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;

/// Client-supplied configuration for a `codex` tool-call.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, Default)]
#[serde(rename_all = "kebab-case")]
pub struct CodexToolCallParam {
    /// The *initial user prompt* to start the Codex conversation.
    pub prompt: String,

    /// Optional override for the model name (e.g. 'gpt-5.2', 'gpt-5.2-codex').
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,

    /// Configuration profile from config.toml to specify default options.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,

    /// Working directory for the session. If relative, it is resolved against
    /// the server process's current working directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,

    /// Approval policy for shell commands generated by the model:
    /// `untrusted`, `on-failure`, `on-request`, `never`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_policy: Option<CodexToolCallApprovalPolicy>,

    /// Sandbox mode: `read-only`, `workspace-write`, or `danger-full-access`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<CodexToolCallSandboxMode>,

    /// Individual config settings that will override what is in
    /// CODEX_HOME/config.toml.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<HashMap<String, serde_json::Value>>,

    /// The set of instructions to use instead of the default ones.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_instructions: Option<String>,

    /// Developer instructions that should be injected as a developer role message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub developer_instructions: Option<String>,

    /// Prompt used when compacting the conversation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compact_prompt: Option<String>,
}

/// Custom enum mirroring [`AskForApproval`], but has an extra dependency on
/// [`JsonSchema`].
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum CodexToolCallApprovalPolicy {
    Untrusted,
    OnFailure,
    OnRequest,
    Never,
}

impl From<CodexToolCallApprovalPolicy> for AskForApproval {
    fn from(value: CodexToolCallApprovalPolicy) -> Self {
        match value {
            CodexToolCallApprovalPolicy::Untrusted => AskForApproval::UnlessTrusted,
            CodexToolCallApprovalPolicy::OnFailure => AskForApproval::OnFailure,
            CodexToolCallApprovalPolicy::OnRequest => AskForApproval::OnRequest,
            CodexToolCallApprovalPolicy::Never => AskForApproval::Never,
        }
    }
}

/// Custom enum mirroring [`SandboxMode`] from config_types.rs, but with
/// `JsonSchema` support.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum CodexToolCallSandboxMode {
    ReadOnly,
    WorkspaceWrite,
    DangerFullAccess,
}

impl From<CodexToolCallSandboxMode> for SandboxMode {
    fn from(value: CodexToolCallSandboxMode) -> Self {
        match value {
            CodexToolCallSandboxMode::ReadOnly => SandboxMode::ReadOnly,
            CodexToolCallSandboxMode::WorkspaceWrite => SandboxMode::WorkspaceWrite,
            CodexToolCallSandboxMode::DangerFullAccess => SandboxMode::DangerFullAccess,
        }
    }
}

/// Builds a `Tool` definition (JSON schema etc.) for the Codex tool-call.
pub(crate) fn create_tool_for_codex_tool_call_param() -> Tool {
    let schema = SchemaSettings::draft2019_09()
        .with(|s| {
            s.inline_subschemas = true;
        })
        .into_generator()
        .into_root_schema_for::<CodexToolCallParam>();

    let input_schema = create_tool_input_schema(schema, "Codex tool schema should serialize");

    Tool {
        name: "codex".into(),
        title: Some("Codex".to_string()),
        input_schema,
        output_schema: Some(codex_tool_output_schema()),
        description: Some(
            "Run a Codex session. Accepts configuration parameters matching the Codex Config struct."
                .into(),
        ),
        annotations: None,
        execution: None,
        icons: None,
        meta: None,
    }
}

fn codex_tool_output_schema() -> Arc<JsonObject> {
    let schema = serde_json::json!({
        "type": "object",
        "properties": {
            "threadId": { "type": "string" },
            "content": { "type": "string" }
        },
        "required": ["threadId", "content"],
    });
    match schema {
        serde_json::Value::Object(map) => Arc::new(map),
        _ => unreachable!("json literal must be an object"),
    }
}

impl CodexToolCallParam {
    /// Returns the initial user prompt to start the Codex conversation and the
    /// effective Config object generated from the supplied parameters.
    pub async fn into_config(
        self,
        arg0_paths: Arg0DispatchPaths,
    ) -> std::io::Result<(String, Config)> {
        let Self {
            prompt,
            model,
            profile,
            cwd,
            approval_policy,
            sandbox,
            config: cli_overrides,
            base_instructions,
            developer_instructions,
            compact_prompt,
        } = self;

        // Build the `ConfigOverrides` recognized by codex-core.
        let overrides = ConfigOverrides {
            model,
            config_profile: profile,
            cwd: cwd.map(PathBuf::from),
            approval_policy: approval_policy.map(Into::into),
            sandbox_mode: sandbox.map(Into::into),
            codex_self_exe: arg0_paths.codex_self_exe.clone(),
            codex_linux_sandbox_exe: arg0_paths.codex_linux_sandbox_exe.clone(),
            main_execve_wrapper_exe: arg0_paths.main_execve_wrapper_exe.clone(),
            base_instructions,
            developer_instructions,
            compact_prompt,
            ..Default::default()
        };

        let cli_overrides = cli_overrides
            .unwrap_or_default()
            .into_iter()
            .map(|(k, v)| (k, json_to_toml(v)))
            .collect();

        let cfg =
            Config::load_with_cli_overrides_and_harness_overrides(cli_overrides, overrides).await?;

        Ok((prompt, cfg))
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct CodexToolCallReplyParam {
    /// DEPRECATED: use threadId instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    conversation_id: Option<String>,

    /// The thread id for this Codex session.
    /// This field is required, but we keep it optional here for backward
    /// compatibility for clients that still use conversationId.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    thread_id: Option<String>,

    /// The *next user prompt* to continue the Codex conversation.
    pub prompt: String,
}

impl CodexToolCallReplyParam {
    pub(crate) fn get_thread_id(&self) -> anyhow::Result<ThreadId> {
        if let Some(thread_id) = &self.thread_id {
            let thread_id = ThreadId::from_string(thread_id)?;
            Ok(thread_id)
        } else if let Some(conversation_id) = &self.conversation_id {
            let thread_id = ThreadId::from_string(conversation_id)?;
            Ok(thread_id)
        } else {
            Err(anyhow::anyhow!(
                "either threadId or conversationId must be provided"
            ))
        }
    }
}

/// Builds a `Tool` definition for the `codex-reply` tool-call.
pub(crate) fn create_tool_for_codex_tool_call_reply_param() -> Tool {
    let schema = SchemaSettings::draft2019_09()
        .with(|s| {
            s.inline_subschemas = true;
        })
        .into_generator()
        .into_root_schema_for::<CodexToolCallReplyParam>();

    let input_schema = create_tool_input_schema(schema, "Codex reply tool schema should serialize");

    Tool {
        name: "codex-reply".into(),
        title: Some("Codex Reply".to_string()),
        input_schema,
        output_schema: Some(codex_tool_output_schema()),
        description: Some(
            "Continue a Codex conversation by providing the thread id and prompt.".into(),
        ),
        annotations: None,
        execution: None,
        icons: None,
        meta: None,
    }
}

fn create_tool_input_schema(schema: Schema, panic_message: &str) -> Arc<JsonObject> {
    #[expect(clippy::expect_used)]
    let mut schema_value = serde_json::to_value(&schema).expect(panic_message);
    normalize_legacy_option_schema(&mut schema_value);
    let mut schema_object = match schema_value {
        serde_json::Value::Object(object) => object,
        _ => panic!("tool schema should serialize to a JSON object"),
    };

    // Prefer keeping the "core" JSON Schema keys while still preserving `$defs`
    // in case any `$ref` leaks into the generated schema (even though we try
    // to inline subschemas).
    let mut input_schema = JsonObject::new();
    for key in ["properties", "required", "type", "$defs", "definitions"] {
        if let Some(value) = schema_object.remove(key) {
            input_schema.insert(key.to_string(), value);
        }
    }

    Arc::new(input_schema)
}

fn normalize_legacy_option_schema(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Array(items) => {
            for item in items {
                normalize_legacy_option_schema(item);
            }
        }
        serde_json::Value::Object(map) => {
            for child in map.values_mut() {
                normalize_legacy_option_schema(child);
            }

            let default_is_null = map.get("default").is_some_and(serde_json::Value::is_null);
            if !default_is_null {
                return;
            }

            if let Some(serde_json::Value::Array(types)) = map.get_mut("type") {
                types.retain(|ty| ty != "null");
                if types.len() == 1
                    && let Some(single_type) = types.pop()
                {
                    map.insert("type".to_string(), single_type);
                }
            }

            let Some(any_of) = map.remove("anyOf") else {
                return;
            };
            let serde_json::Value::Array(variants) = any_of else {
                map.insert("anyOf".to_string(), any_of);
                return;
            };

            let mut non_null_variants = Vec::new();
            let mut removed_null_variant = false;
            for variant in variants {
                if is_null_schema_value(&variant) {
                    removed_null_variant = true;
                } else {
                    non_null_variants.push(variant);
                }
            }

            if removed_null_variant && !non_null_variants.is_empty() {
                map.insert(
                    "allOf".to_string(),
                    serde_json::Value::Array(non_null_variants),
                );
            } else {
                map.insert(
                    "anyOf".to_string(),
                    serde_json::Value::Array(non_null_variants),
                );
            }
        }
        _ => {}
    }
}

fn is_null_schema_value(value: &serde_json::Value) -> bool {
    match value {
        serde_json::Value::Object(map) => match map.get("type") {
            Some(serde_json::Value::String(kind)) => kind == "null",
            Some(serde_json::Value::Array(types)) => {
                !types.is_empty() && types.iter().all(|ty| ty == "null")
            }
            _ => map.get("const").is_some_and(serde_json::Value::is_null),
        },
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;
    use std::collections::BTreeSet;

    fn field<'a>(value: &'a serde_json::Value, key: &str) -> &'a serde_json::Value {
        value
            .get(key)
            .unwrap_or_else(|| panic!("missing field {key:?} in {value:#?}"))
    }

    fn object_field<'a>(
        value: &'a serde_json::Value,
        key: &str,
    ) -> &'a serde_json::Map<String, serde_json::Value> {
        field(value, key)
            .as_object()
            .unwrap_or_else(|| panic!("field {key:?} is not an object in {value:#?}"))
    }

    fn string_field<'a>(value: &'a serde_json::Value, key: &str) -> &'a str {
        field(value, key)
            .as_str()
            .unwrap_or_else(|| panic!("field {key:?} is not a string in {value:#?}"))
    }

    fn required_set(value: &serde_json::Value, key: &str) -> BTreeSet<String> {
        field(value, key)
            .as_array()
            .unwrap_or_else(|| panic!("field {key:?} is not an array in {value:#?}"))
            .iter()
            .map(|entry| {
                entry
                    .as_str()
                    .unwrap_or_else(|| panic!("required entry is not a string in {value:#?}"))
                    .to_string()
            })
            .collect()
    }

    fn type_set(schema: &serde_json::Value) -> BTreeSet<String> {
        match field(schema, "type") {
            serde_json::Value::String(kind) => BTreeSet::from([kind.clone()]),
            serde_json::Value::Array(kinds) => kinds
                .iter()
                .map(|entry| {
                    entry
                        .as_str()
                        .unwrap_or_else(|| panic!("type entry is not a string in {schema:#?}"))
                        .to_string()
                })
                .collect(),
            other => panic!("unexpected type field {other:#?} in {schema:#?}"),
        }
    }

    fn enum_set(schema: &serde_json::Value) -> BTreeSet<String> {
        field(schema, "enum")
            .as_array()
            .unwrap_or_else(|| panic!("enum is not an array in {schema:#?}"))
            .iter()
            .map(|entry| match entry {
                serde_json::Value::String(value) => value.clone(),
                serde_json::Value::Null => "null".to_string(),
                other => panic!("unexpected enum entry {other:#?} in {schema:#?}"),
            })
            .collect()
    }

    fn normalized_whitespace(text: &str) -> String {
        text.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    fn assert_tool_output_schema(output_schema: &serde_json::Value) {
        assert_eq!(
            required_set(output_schema, "required"),
            BTreeSet::from(["content".to_string(), "threadId".to_string()])
        );

        let properties = object_field(output_schema, "properties");
        assert_eq!(
            properties.keys().cloned().collect::<BTreeSet<_>>(),
            BTreeSet::from(["content".to_string(), "threadId".to_string()])
        );
        assert_eq!(
            type_set(&properties["content"]),
            BTreeSet::from(["string".to_string()])
        );
        assert_eq!(
            type_set(&properties["threadId"]),
            BTreeSet::from(["string".to_string()])
        );
        assert_eq!(
            type_set(output_schema),
            BTreeSet::from(["object".to_string()])
        );
    }

    /// We include a test to verify the exact JSON schema as "executable
    /// documentation" for the schema. When can track changes to this test as a
    /// way to audit changes to the generated schema.
    ///
    /// Seeing the fully expanded schema makes it easier to casually verify that
    /// the generated JSON for enum types such as "approval-policy" is compact.
    /// Ideally, modelcontextprotocol/inspector would provide a simpler UI for
    /// enum fields versus open string fields to take advantage of this.
    ///
    /// As of 2025-05-04, there is an open PR for this:
    /// https://github.com/modelcontextprotocol/inspector/pull/196
    #[test]
    fn verify_codex_tool_json_schema() {
        let tool = create_tool_for_codex_tool_call_param();
        let tool_json = serde_json::to_value(&tool).expect("tool serializes");

        assert_eq!(string_field(&tool_json, "name"), "codex");
        assert_eq!(string_field(&tool_json, "title"), "Codex");
        assert_eq!(
            string_field(&tool_json, "description"),
            "Run a Codex session. Accepts configuration parameters matching the Codex Config struct."
        );

        let input_schema = field(&tool_json, "inputSchema");
        assert_eq!(
            required_set(input_schema, "required"),
            BTreeSet::from(["prompt".to_string()])
        );
        assert_eq!(
            type_set(input_schema),
            BTreeSet::from(["object".to_string()])
        );

        let properties = object_field(input_schema, "properties");
        assert_eq!(
            properties.keys().cloned().collect::<BTreeSet<_>>(),
            BTreeSet::from([
                "approval-policy".to_string(),
                "base-instructions".to_string(),
                "compact-prompt".to_string(),
                "config".to_string(),
                "cwd".to_string(),
                "developer-instructions".to_string(),
                "model".to_string(),
                "profile".to_string(),
                "prompt".to_string(),
                "sandbox".to_string(),
            ])
        );

        assert_eq!(
            type_set(&properties["prompt"]),
            BTreeSet::from(["string".to_string()])
        );
        assert_eq!(
            normalized_whitespace(string_field(&properties["prompt"], "description")),
            "The *initial user prompt* to start the Codex conversation."
        );

        for key in [
            "model",
            "profile",
            "cwd",
            "base-instructions",
            "developer-instructions",
            "compact-prompt",
        ] {
            assert_eq!(
                type_set(&properties[key]),
                BTreeSet::from(["null".to_string(), "string".to_string()]),
                "unexpected type for {key}"
            );
        }

        assert_eq!(
            type_set(&properties["config"]),
            BTreeSet::from(["null".to_string(), "object".to_string()])
        );
        assert_eq!(
            field(&properties["config"], "additionalProperties"),
            &serde_json::Value::Bool(true)
        );

        assert_eq!(
            type_set(&properties["approval-policy"]),
            BTreeSet::from(["null".to_string(), "string".to_string()])
        );
        assert_eq!(
            enum_set(&properties["approval-policy"]),
            BTreeSet::from([
                "never".to_string(),
                "null".to_string(),
                "on-failure".to_string(),
                "on-request".to_string(),
                "untrusted".to_string(),
            ])
        );
        assert_eq!(
            normalized_whitespace(string_field(&properties["approval-policy"], "description")),
            "Approval policy for shell commands generated by the model: `untrusted`, `on-failure`, `on-request`, `never`."
        );

        assert_eq!(
            type_set(&properties["sandbox"]),
            BTreeSet::from(["null".to_string(), "string".to_string()])
        );
        assert_eq!(
            enum_set(&properties["sandbox"]),
            BTreeSet::from([
                "danger-full-access".to_string(),
                "null".to_string(),
                "read-only".to_string(),
                "workspace-write".to_string(),
            ])
        );

        assert_tool_output_schema(field(&tool_json, "outputSchema"));
    }

    #[test]
    fn verify_codex_tool_reply_json_schema() {
        let tool = create_tool_for_codex_tool_call_reply_param();
        let tool_json = serde_json::to_value(&tool).expect("tool serializes");

        assert_eq!(string_field(&tool_json, "name"), "codex-reply");
        assert_eq!(string_field(&tool_json, "title"), "Codex Reply");
        assert_eq!(
            string_field(&tool_json, "description"),
            "Continue a Codex conversation by providing the thread id and prompt."
        );

        let input_schema = field(&tool_json, "inputSchema");
        assert_eq!(
            required_set(input_schema, "required"),
            BTreeSet::from(["prompt".to_string()])
        );
        assert_eq!(
            type_set(input_schema),
            BTreeSet::from(["object".to_string()])
        );

        let properties = object_field(input_schema, "properties");
        assert_eq!(
            properties.keys().cloned().collect::<BTreeSet<_>>(),
            BTreeSet::from([
                "conversationId".to_string(),
                "prompt".to_string(),
                "threadId".to_string(),
            ])
        );

        assert_eq!(
            type_set(&properties["prompt"]),
            BTreeSet::from(["string".to_string()])
        );
        assert_eq!(
            normalized_whitespace(string_field(&properties["prompt"], "description")),
            "The *next user prompt* to continue the Codex conversation."
        );

        for key in ["conversationId", "threadId"] {
            assert_eq!(
                type_set(&properties[key]),
                BTreeSet::from(["null".to_string(), "string".to_string()])
            );
        }
        assert_eq!(
            normalized_whitespace(string_field(&properties["conversationId"], "description")),
            "DEPRECATED: use threadId instead."
        );
        assert_eq!(
            normalized_whitespace(string_field(&properties["threadId"], "description")),
            "The thread id for this Codex session. This field is required, but we keep it optional here for backward compatibility for clients that still use conversationId."
        );

        assert_tool_output_schema(field(&tool_json, "outputSchema"));
    }
}
